# config/services.yaml
services:
  _defaults:
    autowire: true      # inyecta automáticamente dependencias
    autoconfigure: true # registra automáticamente comandos, listeners, etc.

  # Registra todas las clases de src/
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Servicio específico para TenantDatabaseManager
  App\Service\TenantDatabaseManager:
    arguments:
      $defaultEm: '@doctrine.orm.entity_manager'